### ISSUE TITLE
Throw error if source or target does not exist

### ISSUE THREAD

**Issue by FractalizeR** [kevlened/copy-webpack-plugin#12] opened 2016-01-23 20:15 UTC
Plugin doesn't copy anything anywhere for me and I guess I made a mistake in paths. I guess this should be an error in the plugin when `from` or` to` is not recognized as a correct, accessible file or directory.

**Comment by kevlened** [comment] 2016-01-24 02:03
Seems like a duplicate of #11

**Closed by kevlened** 2016-01-24 02:03 UTC

**Comment by FractalizeR** [comment] 2016-01-24 09:55
I am not sure this is a duplicate. Debugging info is a one thing. But throwing an error if source or target folder does not exist - is another one.
