### ISSUE TITLE
not copy the files in node v 6.0.0

### ISSUE THREAD

**Issue by OnionCoder** [kevlened/copy-webpack-plugin#39] opened 2016-04-28 17:29 UTC
This is my plugin configuration: 

```
new CopyWebpackPlugin([
   { from: 'src/image', to: 'image' },
   { from: 'src/vendor', to: 'vendor' }
])
```

It works fine with node v 5.8.1 but it does not copy any file with node v 6.0.0.

Webpack shows 'ERROR in Path must be a string. Received undefined' in the console.

**Comment by OnionCoder** [comment] 2016-04-29 14:29
Hi, I used 1.1 version before. I just tested with the newest version 2.1.3, still get the same problem.

**Comment by kevlened** [comment] 2016-05-01 21:30
This is because we use gulp to build underneath, which has an underlying issue: https://github.com/gulpjs/gulp/issues/1571

**Comment by Krisa** [comment] 2016-05-09 10:19
I guess in the meantime it would be good to warn people in the readme of this issue (that the plugin is not compatible with node v6) - and/or additionally providing a meaningful error message in the webpack output (e.g. "CopyWebpackPlugin is not yet compatible with Node v6"). Nailing down the issue of why my relatively complex webpack build was failing due to this plugin was really not a quick one...

**Comment by amgohan** [comment] 2016-05-10 21:37
any news with this bug?

**Comment by kevlened** [comment] 2016-05-13 06:37
This should be resolved in v2.1.4

**Comment by landed1** [comment] 2016-05-13 08:13
I am using node v 6.0.0 and not getting major issues. I have not fully got what I needed fixed with an error like Cannot read property 'glob' of undefined but this isnt all the time...

**Closed** 2016-05-19 02:30 UTC
Labels: bug

**Comment by aanavaneeth** [comment] 2016-05-23 09:37
I am using node 0.12 & I am having this issue

**Comment by V-Tom** [comment] 2017-06-06 07:00
any news with this issue?
same on node v8.0

**Comment by christopherallanperry** [comment] 2018-03-31 15:02
Same here on v8.10.0

**Comment by evilebottnawi** [comment] 2018-03-31 15:16
@christopherallanperry can you create new issue and create minimum reproducible test repo?

**Comment by christopherallanperry** [comment] 2018-04-01 21:35
@evilebottnawi in the process of creating the repo, I was able to resolve whatever was causing the problem, though I'm unsure how. Apologies for any inconvenience caused.
