### ISSUE TITLE
"Error: EMFILE: too many open files, open.." on Windows 

### ISSUE THREAD

**Issue by TimNZ** [kevlened/copy-webpack-plugin#59] opened 2016-06-21 01:30 UTC
That's pretty much the issue.  
Works fine on OS X

Have googled and can't find any way to increase Windows open file limit.
Is now also happening on OS X 'ENFILE: file table overflow'

As far as I can tell this module always works down to an individual file level in async.

I've worked around this by changing the app structure (it will be the ~8000 files in node_modules) and doing a shell cp instead.

Is it something you need to look at handling via something like graceful-fs?

**Comment by qiaolb** [comment] 2016-06-24 02:12
I have a same problem.

**Comment by kevlened** [comment] 2016-06-25 18:35
This is tricky, because [node-glob no longer uses graceful-fs](https://github.com/isaacs/node-glob/issues/71) and just including it before node-glob won't work because [graceful-fs has stopped monkey-patching fs](https://github.com/isaacs/node-graceful-fs#v4). The [graceful-fs docs say not to patch fs in a library](https://github.com/isaacs/node-graceful-fs#global-patching) (like this one), so it'd have to be added as an option. The problem is, the option would have to be checked before any other module loaded fs. An environment variable is the only reasonable way I can think to do that, which seems sloppy.

If you're running into this issue, you'll need to monkey-patch fs yourself. Here's how:

    // At the top of your webpack config, insert this
    var fs = require('fs');
    var gracefulFs = require('graceful-fs');
    gracefulFs.gracefulify(fs);

I'd add this info to the docs.

**Comment by TimNZ** [comment] 2016-06-25 22:05
The irony of me suggesting graceful-fs based on comments I real elsewhere for different issues and then never looking at the module myself and seeing that it would help :)

**Comment by kevlened** [comment] 2016-06-26 01:15
No worries! Others had the same issue, so I'm glad it's in the docs now.

**Comment by keyiis** [comment] 2016-07-05 07:54
@kevlened i have same issues,i already monkey-patch fs,below is my code:
```
var fs = require('fs');
var gracefulFs = require('graceful-fs');
gracefulFs.gracefulify(fs);
const webpackMerge = require('webpack-merge');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const commonConfig = require('./webpack.common.js');
const helpers = require('./helpers');

module.exports = webpackMerge(commonConfig, {
  ......
plugins: [
    new CopyWebpackPlugin([
      { from: helpers.root('node_modules/ckeditor/ckeditor.js'), to: 'node_modules/ckeditor' },
      { from: helpers.root('node_modules/ckeditor/config.js'), to: 'node_modules/ckeditor' },
      { from: helpers.root('node_modules/ckeditor/styles.js'), to: 'node_modules/ckeditor' },
      { from: helpers.root('node_modules/ckeditor/contents.css'), to: 'node_modules/ckeditor' },
      { from: helpers.root('node_modules/ckeditor/skins/moono'), to: 'node_modules/ckeditor/skins/moono' },
      { from: helpers.root('node_modules/ckeditor/lang/zh-cn.js'), to: 'node_modules/ckeditor/lang' },
      { from: helpers.root('node_modules/ckeditor/plugins'), to: 'node_modules/ckeditor/plugins' },
      { from: helpers.root('node_modules/ckeditor/adapters'), to: 'node_modules/ckeditor/adapters' },
    ])
  ]
}
```
error msg:
 ```
95% emittingfs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open 'D:\work\nodejs\angular\angular2-electron\node_modules\ckeditor\plugins\sourcedialog\lang\ar.js'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.source (D:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\copy-webpack-plugin\3.0.1\copy-webpack-plugin\dist\writeFileToAssets.js:45:31)
    at Compiler.writeOut (D:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compiler.js:290:26)
    at D:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\mkdirp\0.5.1\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by kb3eua** [comment] 2016-07-27 12:41
@kevlened I'm seeing the same issue that @keyiis is reporting.  Even after applying this patch, the error still occurs when trying to copy the "ckeditor" folder.

**Comment by jgrosso** [comment] 2016-07-29 16:16
+1

**Comment by keyiis** [comment] 2016-07-30 05:45
@kb3eua I use gulp to copy file.

**Comment by kb3eua** [comment] 2016-08-01 16:30
@keyiis I didn't want to introduce another task runner.  I was able to get it working by upgrading to the latest version of this plugin and using the following configuration to ignore certain files:

```
 new CopyWebpackPlugin([{
    from: './node_modules/ckeditor',
    to: './dist/scripts/ckeditor',
    ignore: [
        '**/samples/**',
        '**/lang/!(en.js)'
    ]
}]);
```

**Comment by tallaxes** [comment] 2016-09-20 21:40
Having the same error on Windows with many files. graceful-fs does not help, most likely because it does not patch readFileSync/openSync codepath. Webpack's Compiler emitFiles uses [unconstrained async.ForEach](https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L300) over assets, hitting the Node limit on open files (2048 on Windows, due to use of CRT).

`require("async").forEach(Object.keys(compilation.assets), function(file, callback) {`

I don't understand webpack/copy-webpack-plugin/graceful-fs well enough to suggest the right way of fixing this, but constraining webpack to a reasonable number of async operations (using forEachLimit) works fine:

`require("async").forEachLimit(Object.keys(compilation.assets), 2000, function(file, callback) {
`

**Comment by id0Sch** [comment] 2016-09-21 15:07
having this issue on OSX (patch applied and all)

**Comment by McPo** [comment] 2016-10-19 16:39
This is still very much an issue, the monkey patch does not work.
Can we get this issue reopened for visibility @kevlened.

Ive looked into it, but am still clueless as to fix.

**Comment by McPo** [comment] 2016-10-19 17:35
@tallaxes path does work, although I needed a much lower limit (100). Patching WebPack itself also isn't ideal.

The file that needs to be patched is ./node_modules/webpack/lib/Compiler.js.
Make sure not to forget the closing bracket.

Thanks @tallaxes, Im still looking for a more elegant solution though. I doubt Webpack themselves will accept a PR when the number is variable.

**Comment by tallaxes** [comment] 2016-10-19 18:02
@McPo Webpack: It is still worth bringing it to their attention, I think. And there could be ways of coming up with a reasonable number, or just making it configurable.

100 seems unreasonably low; wonder what would limit it like that... For OSX/Linux: did you check OS-level file descriptor limits (i.e. `ulimit -n`)?

**Comment by McPo** [comment] 2016-10-19 18:57
@tallaxes done.
https://github.com/webpack/webpack/issues/3164

Ive bumped it back up to 1000 it works fine. I supposed my machine is not under heavy load, having said that, lowering it to 100 had no adverse effect on build time.

**Comment by keyiis** [comment] 2016-10-20 00:38
My issues looks like the floder has symlink,resulting in a circular dependency,but I'm not sure.

**Comment by McPo** [comment] 2016-10-20 14:49
Ive created a PR. for those suffering from this issue you can use it right away by setting your package.json to

"webpack": "McPo/webpack#1.13.2-file-limit"

Ive limited to 1000, but perhaps 500 is more reasonable.
You can to set it to a user defined value using the environment variable WEBPACK_FILE_LIMIT

https://github.com/webpack/webpack/pull/3166

**Comment by kevlened** [comment] 2016-10-20 15:38
The upcoming version of copy-webpack-plugin (currently in master) avoids `fs.readFileSync`, which is the main source of the issue, because it isn't patched by graceful-fs. That should allow graceful-fs to be a proper solution.

For additional control, I've added a concurrency option that will allow changing how many files the plugin attempts to read at once (currently set to a default of 1000, but it sounds like that should be reduced). Does 100 sound like a reasonable default?

**Comment by kevlened** [comment] 2016-10-23 20:17
This should be fixed in the latest version (v4.0.0). We avoid `fs.readFileSync`, so graceful-fs can now patch the issue, but there are also extra measures to ensure we don't read too many files at once (a `concurrency` option, which defaults to 100). I'm closing this for now, but if you encounter the error after upgrading to v4.0.0, I'll reopen.

**Closed by kevlened** 2016-10-23 20:17 UTC
Labels: bug

**Comment by irjigeiler** [comment] 2017-03-18 15:16
still get this error on 4.0.1

**Comment by jf990** [comment] 2017-08-29 23:39
I upgraded to Node 8 and the EMFILE error went away.

**Comment by Cjhome** [comment] 2018-08-17 02:39
This error can be due to a configuration file error or a parameter filling error while configuring webpack

**Comment by joeyparis** [comment] 2019-09-17 18:29
I'm running into this problem with webpack 4.4.1 and node 10.5
